= Java 各种O的意思

PO：持久对象 (persistent object)，po(persistent object)就是在Object/Relation Mapping框架中的Entity。

    po的每个属性基本上都对应数据库表里面的某个字段。
    完全是一个符合Java Bean规范的纯Java对象，没有增加别的属性和方法。持久对象是由insert数据库创建，由数据库delete删除的。基本上持久对象生命周期和数据库密切相关。

VO：

    * 值对象(Value Object)，通常用于业务层之间的数据传递，和PO一样也是仅仅包含数据而已。但应是抽象出的业务对象，可以和表对应，也可以不，这根据业务的需要。

    * 表现层对象(View Object)，主要对应展示界面显示的数据对象，用一个VO对象来封装整个界面展示所需要的对象数据。

BO：业务对象层的缩写(Business Object)，封装业务逻辑的java对象，通过调用DAO方法，结合PO,VO进行业务操作。

    具体可以看网上的一个例子：
    比如一个简历，有教育经历、工作经历、社会关系等等。
    我们可以把教育经历对应一个PO，工作经历对应一个PO，社会关系对应一个PO。
    建立一个对应简历的BO对象处理简历，每个BO包含这些PO。
    这样处理业务逻辑时，我们就可以针对BO去处理。

DTO：数据传输对象(Data Transfer Object)，是一种设计模式之间传输数据的软件应用系统。

    数据传输目标往往是数据访问对象从数据库中检索数据。数据传输对象与数据交互对象或数据访问对象之间的差异是一个以不具有任何行为除了存储和检索的数据（访问和存取器）。简单来说，当我们需要一个对象10个字段的内容，但这个对象总共有20个字段，我们不需要把整个PO对象全部字段传输到客户端，而是可以用DTO重新封装，传递到客户端。此时，如果这个对象用来对应界面的展现，就叫VO。


POJO：POJO（Plain Ordinary Java Object）简单的Java对象，实际就是普通JavaBeans，是为了避免和EJB混淆所创造的简称。通指没有使用Entity Beans的普通java对象，可以把POJO作为支持业务逻辑的协助类。
POJO实质上可以理解为简单的实体类，顾名思义POJO类的作用是方便程序员使用数据库中的数据表，对于广大的程序员，可以很方便的将POJO类当做对象来进行使用，当然也是可以方便的调用其get,set方法。POJO类也给我们在struts框架中的配置带来了很大的方便。
一个POJO持久化以后就是PO
直接用它传递、传递过程中就是DTO
直接用来对应表示层就是VO

DAO: 数据访问对象是第一个面向对象的数据库接口，是一个数据访问接口(Data Access Object)。它可以把POJO持久化为PO，用PO组装出来VO、DTO。
DAO模式是标准的J2EE设计模式之一.开发人员使用这个模式把底层的数据访问操作和上层的商务逻辑分开.一个典型的DAO实现有下列几个组件：

    1. 一个DAO工厂类；
    2. 一个DAO接口；
    3. 一个实现DAO接口的具体类；
    4. 数据传递对象（有些时候叫做值对象）.

具体的DAO类包含了从特定的数据源访问数据的逻辑，一般一个DAO类和一张表对应，每个操作要和事务关联。